---
- name: "Creates backend app dir"
  file:
    path: ~/backend-app
    state: directory


- name: "Unarchive backend files"
  unarchive:
    src: ~/project/.circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: ~/backend-app

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
   sudo env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu